#include "app/exporter/stlexporter.h"

#include <cstring>
#include <fstream>
#include <vector>
#include <glm/geometric.hpp>

#include "app/bcifs/bcifs.h"
#include "app/bcifs/bcifsvertex.h"

void STLExporter::exportBinary(const std::string& filename, BCIFS::Bcifs& bcifs, std::size_t iterationLevel) {
    std::ofstream file(filename, std::ios::binary);

    if (!file)
        throw std::runtime_error("Cannot open STL file");

    char header[80] = {};
    std::string text = "Binary STL generated by AutoFrac";
    std::memcpy(header, text.c_str(), text.size());
    file.write(header, 80);

    std::vector<std::vector<BCIFS::BcifsVertex>> faces = bcifs.faces(iterationLevel);
    std::size_t nbTriangles = 0;
    for (const std::vector<BCIFS::BcifsVertex>& face : faces) {
        nbTriangles += face.size() > 3 ? face.size() : 1;
    }
    file.write(reinterpret_cast<char*>(&nbTriangles), 4);

    for (const std::vector<BCIFS::BcifsVertex>& vertices : faces) {
        if (vertices.size() == 3) {
            const glm::vec3& v0 = vertices[0].pos();
            const glm::vec3& v1 = vertices[1].pos();
            const glm::vec3& v2 = vertices[2].pos();
            glm::vec3 normal = glm::normalize(glm::cross(v1 - v0, v2 - v0));

            writeVec3(file, normal);
            writeVec3(file, v0);
            writeVec3(file, v1);
            writeVec3(file, v2);

            uint16_t attribute = 0;
            file.write(reinterpret_cast<char*>(&attribute), 2);
        } else {
            glm::vec3 barycenter{ 0, 0, 0 };
            for (const BCIFS::BcifsVertex& vertex : vertices) {
                barycenter += vertex.pos();
            }
            barycenter /= static_cast<float>(vertices.size());

            for (std::size_t i = 0; i < vertices.size(); i++) {
                const glm::vec3& v1 = vertices[i].pos();
                const glm::vec3& v2 = vertices[(i + 1) % vertices.size()].pos();
                glm::vec3 normal = glm::normalize(glm::cross(v1 - barycenter, v2 - barycenter));

                writeVec3(file, normal);
                writeVec3(file, barycenter);
                writeVec3(file, v1);
                writeVec3(file, v2);

                uint16_t attribute = 0;
                file.write(reinterpret_cast<char*>(&attribute), 2);
            }
        }
    }
}

void STLExporter::writeVec3(std::ofstream& file, const glm::vec3& v) {
    file.write(reinterpret_cast<const char*>(&v.x), sizeof(float));
    file.write(reinterpret_cast<const char*>(&v.y), sizeof(float));
    file.write(reinterpret_cast<const char*>(&v.z), sizeof(float));
}
